#!/usr/bin/env sh

set -e

echo 'Building Docs 🚀'

# General Hooks
npx jsdoc2md --files src/hooks/useId.js -g grouped > src/hooks/useId.md
npx jsdoc2md --files src/hooks/useTimeout.js -g grouped > src/hooks/useTimeout.md
npx jsdoc2md --files src/hooks/useEnterExit.js -g grouped > src/hooks/useEnterExit.md
# Aria Hooks
npx jsdoc2md --files src/hooks/aria/*.js -g grouped > src/hooks/aria/ARIA.md
# Analytics
npx jsdoc2md --files src/hooks/analytics/analytics.js -g grouped > src/hooks/analytics/API.md
# Number Utils
npx jsdoc2md --files src/components/numbers/number-util.js -g grouped > src/components/numbers/number-util.md
# General Utils
npx jsdoc2md --files src/utils/*.js -g grouped > src/utils/UTILS.md

echo 'Donzo 💪'
